spring.application.name=einvoice-backend

spring.datasource.url=jdbc:postgresql://3.111.233.209:5432/tronsync
spring.datasource.username=postgres
spring.datasource.password=P0stgres@582
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
app.base-url=http://localhost:5173
